 spring:
  port: 8081
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voj
    username: root
    password: 8888888
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
